In [1]:
import numpy as np

*Vectors*

In [2]:
v1 = np.array([1,2,3])

v2 = np.array([4,5,6])

print(f"v1 = {v1} ,v2 = {v2}")

v1 = [1 2 3] ,v2 = [4 5 6]


In [5]:
v3 = v1 + v2
v3_ = v1 - v2

print(f"v3 = {v3} [-  {v3_}]")

v3 = [5 7 9] [-  [-3 -3 -3]]


In [4]:
v4 = np.dot(v1,v2)

print(f"Vector dot product {v4}")

Vector dot product 32


In [12]:
#L2
v5 = np.linalg.norm(v1)
print(v5)

sum=0
for i in v1:
    sum+=(i**2)
L2 = sum ** 0.5
print(L2)

L2_ = np.sqrt((np.sum(v1 ** 2)))
print(L2_)

3.7416573867739413
3.7416573867739413
3.7416573867739413


In [ ]:
#L1
v5_ = np.linalg.norm(v1,1)
print(v5_)

6.0


*Matrices*

In [ ]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
m3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# '[]' Row , ',' Column
print(m1)
print(m2)
print(m3)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
A = m1 + m2
B = m1 - m2
print(A)
print(B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [39]:
E = m1 * m2
print(E)
F = np.dot(m1,m2)
print(F)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [49]:
def check(m1,m2):
    row1,col1=m1.shape
    row2,col2=m2.shape
    print(f"{row1}, {col1}")
    print(f"{row2}, {col2}")
    # r = np.zeros((row1,col2))
    # print(r)
    if col1 != row2:
        return -1
    _F = np.dot(m1,m2)
    return _F
    

mt1 = np.array([[7,8],[9,10],[11,12]])
mt2 = np.array([[1,2,3],[4,5,6]])

print(check(mt2,mt1))

2, 3
3, 2
[[ 58  64]
 [139 154]]


In [47]:
F = np.transpose(mt1)
print(mt1)
print(F)
print(mt1.T)

[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 7  9 11]
 [ 8 10 12]]
[[ 7  9 11]
 [ 8 10 12]]


In [52]:
mt3 = np.array([[7,8],[9,10]])

det_mt3 = np.linalg.det(mt3)
print(det_mt3)

-2.000000000000009


In [68]:
def Miners(Mt1):
    row1 ,col1=Mt1.shape
    if(row1 != col1):
        return -1
    if(row1==2):
        result = abs(Mt1[0][0] * Mt1[1][1] - Mt1[0][1] * Mt1[1][0])
        print(result)
    else :
        # for i in range(col1):
        #     for j in range(row1):
        #         result = Mt1[j][i] * abs(Mt1[j+1][i+1] * Mt1[j+2][i+2] - Mt1[j+1][i+2] * Mt1[j+2][i+1])
        #         print(result)
        result=0
        result += Mt1[0][0] * (abs(Mt1[1][1] * Mt1[2][2] - Mt1[1][2] * Mt1[2][1]))
        result += (-1 * Mt1[0][1]) * (abs(Mt1[1][0] * Mt1[2][2] - Mt1[1][2] * Mt1[2][0]))
        result += Mt1[0][2] * (abs(Mt1[1][0] * Mt1[2][1] - Mt1[1][1] * Mt1[2][0]))
        print(result)


mt3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#mt3 = np.array([[1,2],[3,4]])

F = np.linalg.det(mt3)
print(round(F))
Miners(mt3)

0
0


In [98]:
def get_minor(matrix,row,col):
    minor=np.delete(matrix,row,axis=0)
    minor = np.delete(minor,col,axis=1)
    # print(minor)
    return minor

def cal_det(matrix):
    if matrix.shape[0]==matrix.shape[0] and matrix.shape[0] == 2:
        return matrix[0,0] * matrix[1,1] - matrix[0,1] * matrix[1,0]
    elif matrix.shape[0]==matrix.shape[0]:
        determinant =0
        for c in range(matrix.shape[1]):
            minor = get_minor(matrix,0,c)
            determinant += ((-1)** c) * matrix[0,c] * cal_det(minor)
        return determinant

#mt3 = np.array([[2,1,3,4],[5,6,7,8],[9,10,12,11],[13,14,16,15]])
mt3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#mt3 = np.array([[1,2],[3,4]])

F = np.linalg.det(mt3)
print(round(F))
print(cal_det(mt3))

0
0


In [107]:
def inverse(matrix):
    if matrix.shape[0]==matrix.shape[0] and matrix.shape[0] == 2:
        det = cal_det(matrix)
        if det == 0:
            print("Error")
            return
        a, b, c, d = matrix[0,0], matrix[0,1], matrix[1,0], matrix[1,1]
        return np.array([[d, -b], [-c, a]]) / det
    
    elif matrix.shape[0]==matrix.shape[0]:
        det = cal_det(matrix)
        if det == 0:
            print("Error")
            return
        cofactor_matrix = np.zeros((matrix.shape[0], matrix.shape[0]))
        
        for i in range(matrix.shape[0]):
            for j in range(matrix.shape[0]):
                minor = get_minor(matrix, i, j)
                cofactor_matrix[i, j] = ((-1) ** (i + j)) * cal_det(minor)
        
        adjugate_matrix = cofactor_matrix.T
        inverse_matrix = adjugate_matrix / det
        
        return inverse_matrix

mt3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#mt3 = np.array([[1,2],[3,4]])
inv_mt3 = np.linalg.inv(mt3)
_inv_mt3 = inverse(mt3)
print(inv_mt3)
print(_inv_mt3)
# print(np.dot(mt3, _inv_mt3))

Error
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
None
